final List<Map<String, String>> stackItems = [
  {'title': 'Flutter', 'icon': 'assets/flutter1.png'},
  {'title': 'mongodeb', 'icon': 'assets/mongodb.png'},
  {'title': 'flask', 'icon': 'assets/flask.png'},
  {'title': 'django', 'icon': 'assets/django.png'},
  {'title': 'pdsql', 'icon': 'assets/pdsql.png'},
  {'title': 'Firebase', 'icon': 'assets/firebase.png'},
  {'title': 'supabase', 'icon': 'assets/supabase.png'},
  {'title': 'go', 'icon': 'assets/go.png'},
  {'title': 'Python', 'icon': 'assets/python.png'},
  {'title': 'Dart', 'icon': 'assets/dart.png'},
  {'title': 'Git', 'icon': 'assets/git.png'},
  {'title': 'Java', 'icon': 'assets/linux.png'},
  {'title': 'tensorflow', 'icon': 'assets/tensorflow.png'},
  {'title': 'scikitlearn', 'icon': 'assets/scikitlearn.png'},
  {'title': 'pandas', 'icon': 'assets/pandas.png'},
  {'title': 'numpy', 'icon': 'assets/numpy.png'},
  // {'title': 'numpy', 'icon': 'assets/numpy.png'},
  // {'title': 'numpy', 'icon': 'assets/numpy.png'},
];
